import img from '../assets/img/image.webp'
export const categories = [
    {
        id: 1,
        name: 'Мужчинам',
        img: img,
        children: [],
    },
    {
        id: 2,
        name: 'Женщинам',
        img: img,
        children: [],
    },
    {
        id: 3,
        name: 'Спорт',
        img: img,
        children: [],
    },
    {
        id: 4,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 5,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 6,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 7,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 8,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 9,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 10,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 11,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 12,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 13,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 14,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 15,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 16,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 17,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 18,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 19,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 20,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 21,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 22,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 23,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 24,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 25,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 26,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 27,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 28,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 29,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 30,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 31,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 32,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 33,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 34,
        name: 'Электроника',
        img: img,
        children: [],
    },
    {
        id: 35,
        name: 'Электроника',
        img: img,
        children: [],
    },
]